openapi: 3.1.0
info:
  title: skyshare lexicon wrapper
  version: 2.0.0
  description: ATProto ClientをAstro SSGで利用するためのAPIラッパー

paths: # APIドキュメントのエンドポイント
  /v1/entry:
    $ref: ./v1/entry/index.yaml
  /v1/session:
    $ref: ./v1/session/index.yaml
  /v1/extract:
    $ref: ./v1/extract/index.yaml
  /v1/drafts:
    $ref: ./v1/drafts/index.yaml
