openapi: 3.1.0
info:
  title: skyshare lexicon wrapper
  version: 2.0.0
  description: ATProto ClientをAstro SSGで利用するためのAPIラッパー

paths: # APIドキュメントのエンドポイント
  /v1/extract:
    $ref: ./v1/extract/index.yaml
  /v2/entry:
    $ref: ./v2/entry/index.yaml
  /v2/session:
    $ref: ./v2/session/index.yaml
  /v2/drafts:
    $ref: ./v2/drafts/index.yaml
  /v1/page:
    delete:
      $ref: ./v1/page/delete.yaml
  /v1/page/{dbIndex}/{dbKey}:
    get:
      $ref: ./v1/page/get.yaml
