name: Auto-change PR Base to Develop

on:
  pull_request:
    types: ["opened", "edited", "reopened"]

jobs:
  change-base:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require("./.github/workflows/auto-change-pr-base.js");
            script({ context, github });
