name: "[OnCall] Get env_name"
run-name: "Get env_name"

on:
  workflow_call:
    outputs:
      env_name:
        description: "Environment value"
        value: ${{ jobs.get_env_name.outputs.env_name }}

jobs:
  get_env_name:
    name: "Get env_name"
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env_name.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Output Environment value
        id: get_env_name
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          else
            echo "env_name=preview" >> $GITHUB_OUTPUT
          fi